projectName: openelis-ai-platform
image: jembi/platform:latest
logPath: /tmp/logs

packages:
  - interoperability-layer-openhim
  - reverse-proxy-nginx
  - fhir-datastore-hapi-fhir
  - monitoring
  - database-postgres

profiles:
  - name: dev
    packages:
      - interoperability-layer-openhim
      - reverse-proxy-nginx
      - fhir-datastore-hapi-fhir
      - monitoring
      - database-postgres
    envFiles:
      - dev.env
